version: '3.6'
services:
  pg:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER : demo
      POSTGRES_DB: demo
      POSTGRES_PASSWORD: demo
    volumes:
      - ${PWD}/pg/pg-scripts:/docker-entrypoint-initdb.d/
    ports:
      - 5432:5432
  jgw:
    build:
      context: jgw
      dockerfile: Dockerfile
    restart: always
    ports: 
      - 2021:55555
  iris:
    build: 
      context: iris
      dockerfile: Dockerfile
    restart: always
    ports: 
      - 51773:51773
      - 52773:52773
