-- AppEvents
CREATE TABLE AppEvents (
	evt_id int NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	evt_type varchar(3) NOT NULL,
	evt_status int NOT NULL,
	evt_dt_creation timestamp NOT NULL,
	evt_dt_process timestamp NULL,
    CONSTRAINT PK_AppEvents PRIMARY KEY (evt_id)
);

INSERT INTO AppEvents (evt_type,evt_status,evt_dt_creation) VALUES ('AAA',0,CURRENT_TIMESTAMP);